/**
 * SWIT Open API
 * This is a SWIT Open Api server.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class ModelChannelResponse (
  created: Option[String] = None,
  description: Option[String] = None,
  hidePrevChat: Option[Int] = None,
  id: Option[String] = None,
  isArchive: Option[Boolean] = None,
  isFavorite: Option[Boolean] = None,
  isHidden: Option[Boolean] = None,
  isMember: Option[Boolean] = None,
  isPrivate: Option[Boolean] = None,
  mgrId: Option[String] = None,
  name: Option[String] = None,
  role: Option[String] = None,
  `type`: Option[String] = None
) extends ApiModel


