/**
 * SWIT Open API
 * This is a SWIT Open Api server.
 *
 * OpenAPI spec version: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class TaskTaskResponse (
  bookmark: Option[String] = None,
  bucketId: Option[String] = None,
  color: Option[String] = None,
  description: Option[String] = None,
  endDate: Option[String] = None,
  id: Option[String] = None,
  priority: Option[String] = None,
  projectId: Option[String] = None,
  startDate: Option[String] = None,
  status: Option[String] = None,
  title: Option[String] = None,
  userId: Option[String] = None
) extends ApiModel


